version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuarios_db
      MYSQL_USER: leo
      MYSQL_PASSWORD: leo123
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: backend_container
    restart: always
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

  frontend:
    image: nginx:alpine
    container_name: frontend_container
    ports:
      - "8081:80"
    volumes:
      - ./codigo:/usr/share/nginx/html:ro
    depends_on:
      - backend
